#!/usr/bin/env python3
"""Generate the shipped overlay folders from src/.

Every design used to be a hand-maintained copy of the same 1800-line file, in
two places each: the folder people get from the repo zip, and the copy the
wizard builds from. Sixteen copies of one file meant sixteen edits per fix and
no way to notice when one of them drifted.

src/ is now the only place anything is written by hand:

    src/core_head.py     everything above the overlay markup
    src/designs/*.html   one file per design, just the markup
    src/core_tail.py       everything below it
    src/launcher/*.bat     the launcher, one copy
    src/config.default.json  the settings file a fresh install starts with

This script stitches those together into <Design>/ and wizard/templates/<Design>/.

It also builds the hosted version of the overlay into docs/, which GitHub Pages
serves. The website uses the very same src/designs/*.html markup, with the
Python server swapped for src/web/engine.js:

    src/web/index.html   the setup page people use to make their OBS link
    src/web/engine.js    the browser port of core_head.py
    src/web/logo.svg     the site icon

Run it after touching anything in src/. CI runs it with --check to make sure the
generated folders in the repo actually match src/.

    python tools/build.py            rebuild everything
    python tools/build.py --check    fail if the repo is out of date
"""

import argparse
import hashlib
import os
import re
import shutil
import sys

DESIGNS = ["Minimal", "Classic", "Sharp", "Wide", "Slash", "Rainbow", "Modern", "Pulse"]
LAUNCHERS = ["overlay.bat"]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
WEB = os.path.join(SRC, "web")
DOCS = os.path.join(ROOT, "docs")

# Windows-only tool, and people open server.py in Notepad to check their
# settings, so everything ships with CRLF endings.
NEWLINE = "\r\n"

BANNER = (
    "# ---------------------------------------------------------------------------\n"
    "# Generated by tools/build.py from src/. Do not edit this file directly -- a\n"
    "# release would overwrite your changes. Edit src/core_head.py, src/core_tail.py\n"
    "# or src/designs/{design}.html instead, then run: python tools/build.py\n"
    "#\n"
    "# Your own settings do NOT live in this file. They live in config.json next to\n"
    "# it, which updates never touch.\n"
    "# ---------------------------------------------------------------------------\n"
)


def read(path):
    with open(path, encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n")


def render_server(design):
    """The full server.py for one design."""
    head = read(os.path.join(SRC, "core_head.py"))
    tail = read(os.path.join(SRC, "core_tail.py"))
    html = read(os.path.join(SRC, "designs", design + ".html"))

    if "__DESIGN__" not in head:
        raise SystemExit("src/core_head.py has lost its __DESIGN__ placeholder")
    head = head.replace("__DESIGN__", design)

    return (
        BANNER.replace("{design}", design)
        + head
        + "\n"
        + 'OVERLAY_HTML = r"""'
        + html
        + '"""\n'
        + tail
    )


# The hooks a design's script is rewired through on the website. Each must be
# found exactly once in every design, or the build stops: a design that quietly
# kept polling a localhost server would just sit on "LOADING" in OBS.
WEB_SWAPS = [
    ("__POLL_MS__", "RankedOverlay.config.refreshMs"),
    ('"__INITIAL_CREATOR_CODE__"', "RankedOverlay.config.creatorCode"),
    ("fetch(url, { cache: 'no-store' })", "RankedOverlay.fetchData(url)"),
]
WEB_POLL = re.compile(r"setInterval\((?:tick|function\(\) \{ tick\(\); \})\s*,\s*POLL_MS\);")


# If engine.js didn't arrive (a network blip as OBS starts, say), the page
# would sit dead until someone refreshed the source by hand. Reload it instead,
# backing off from 5 seconds to a minute so a real outage isn't hammered.
ENGINE_GUARD = (
    "if (!window.RankedEngine) { var n = 0; "
    "try { n = +sessionStorage.getItem('ro-reloads') || 0; sessionStorage.setItem('ro-reloads', n + 1); } catch (e) {} "
    "setTimeout(function () { location.reload(); }, Math.min(60000, 5000 * Math.pow(2, n))); } "
    "else { try { sessionStorage.removeItem('ro-reloads'); } catch (e) {} }"
)


def asset_version(text):
    """Short content hash, so OBS never pairs a new page with an old engine."""
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:10]


def render_web_overlay(design, engine_version):
    """One design as a page of the hosted overlay."""
    html = read(os.path.join(SRC, "designs", design + ".html"))

    for old, new in WEB_SWAPS:
        if html.count(old) != 1:
            raise SystemExit(f"src/designs/{design}.html: expected one {old!r}, found {html.count(old)}")
        html = html.replace(old, new)

    if len(WEB_POLL.findall(html)) != 1:
        raise SystemExit(f"src/designs/{design}.html: expected one setInterval(tick, POLL_MS)")
    html = WEB_POLL.sub("RankedOverlay.onUpdate(tick);", html)

    if html.count("<script>") != 1:
        raise SystemExit(f"src/designs/{design}.html: expected exactly one <script> block")
    html = html.replace(
        "<script>",
        f'<script src="../engine.js?v={engine_version}"></script>\n'
        "    <script>" + ENGINE_GUARD + "</script>\n"
        "    <script>window.RankedOverlay = RankedEngine.startOverlay(location.search);</script>\n"
        "    <script>",
        1,
    )
    html = html.replace(
        "<head>",
        "<head>\n    <!-- Generated by tools/build.py from src/designs/"
        + design + ".html. Edit that file, not this one. -->\n"
        '    <meta name="robots" content="noindex">',
        1,
    )
    return html


def web_outputs():
    """The GitHub Pages site, as ({path: text}, {path: source file to copy})."""
    files, binaries = {}, {}
    engine = read(os.path.join(WEB, "engine.js"))
    version = asset_version(engine)

    files[os.path.join(DOCS, "engine.js")] = engine
    index = read(os.path.join(WEB, "index.html"))
    if index.count("__ENGINE_GUARD__") != 1:
        raise SystemExit("src/web/index.html: expected one __ENGINE_GUARD__")
    files[os.path.join(DOCS, "index.html")] = (
        index.replace("__ENGINE_VERSION__", version).replace("__ENGINE_GUARD__", ENGINE_GUARD))
    files[os.path.join(DOCS, "logo.svg")] = read(os.path.join(WEB, "logo.svg"))
    # Serve the files as they are, without Jekyll looking at them first.
    files[os.path.join(DOCS, ".nojekyll")] = ""

    for design in DESIGNS:
        slug = design.lower()
        files[os.path.join(DOCS, "overlay", slug + ".html")] = render_web_overlay(design, version)
        binaries[os.path.join(DOCS, "previews", slug + ".png")] = os.path.join(ROOT, design, "preview.png")
    return files, binaries


def outputs():
    """Every Windows overlay file this script owns, as {path: text}."""
    files = {}
    launchers = {name: read(os.path.join(SRC, "launcher", name)) for name in LAUNCHERS}
    # Shipped filled in with placeholders so a fresh download has something to
    # edit straight away, rather than making people run the overlay once first.
    config = read(os.path.join(SRC, "config.default.json"))

    for design in DESIGNS:
        server = render_server(design)
        for parent in (ROOT, os.path.join(ROOT, "wizard", "templates")):
            folder = os.path.join(parent, design)
            files[os.path.join(folder, "server.py")] = server
            files[os.path.join(folder, "config.json")] = config
            for name, text in launchers.items():
                files[os.path.join(folder, name)] = text

    return files


def write(path, text, newline=NEWLINE):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline=newline) as f:
        f.write(text)


def same_bytes(a, b):
    try:
        with open(a, "rb") as fa, open(b, "rb") as fb:
            return fa.read() == fb.read()
    except OSError:
        return False


def current(path):
    try:
        with open(path, encoding="utf-8", newline="") as f:
            return f.read().replace("\r\n", "\n")
    except OSError:
        return None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report drift instead of rewriting anything")
    args = ap.parse_args()

    files = outputs()
    web_files, web_binaries = web_outputs()
    stale = [p for p, text in files.items() if current(p) != text]
    stale += [p for p, text in web_files.items() if current(p) != text]
    stale += [dst for dst, src in web_binaries.items() if not same_bytes(dst, src)]

    # Anything left in docs/ that the build no longer makes, e.g. a renamed design.
    owned = set(web_files) | set(web_binaries)
    orphans = []
    if os.path.isdir(DOCS):
        for folder, _dirs, names in os.walk(DOCS):
            for name in names:
                path = os.path.join(folder, name)
                if path not in owned:
                    orphans.append(path)

    total = len(files) + len(web_files) + len(web_binaries)
    if args.check:
        if stale or orphans:
            print("These generated files no longer match src/:\n")
            for p in sorted(stale + orphans):
                print("  " + os.path.relpath(p, ROOT))
            print("\nRun: python tools/build.py")
            return 1
        print(f"Up to date ({total} generated files).")
        return 0

    for p, text in files.items():
        write(p, text)
    for p, text in web_files.items():
        write(p, text, newline="\n")
    for dst, src in web_binaries.items():
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)
    for p in orphans:
        os.remove(p)
    print(f"Wrote {total} files for {len(DESIGNS)} designs (including the website in docs/).")
    if stale:
        print(f"{len(stale)} of them changed.")
    if orphans:
        print(f"Removed {len(orphans)} stale file(s) from docs/.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
