#!/usr/bin/env python3
"""Build the website (docs/, served by GitHub Pages) from src/.

src/ is the only place anything is written by hand:

    src/designs/*.html   one file per design, just the overlay markup
    src/web/index.html   the setup page people use to make their OBS link
    src/web/engine.js    fetches OliTracker (through the Worker in web/) and
                         works out everything the designs show
    src/web/logo.svg     the site icon (favicon-32.png and apple-touch-icon.png
                         are renders of it)
    src/web/og.png       the picture link previews show (Discord, X, ...)

plus the design previews the setup page shows, in images/<design>.png.

Each design becomes docs/overlay/<design>.html with its data hooks rewired to
engine.js. Run it after touching anything in src/. CI runs it with --check to
make sure docs/ actually matches src/.

    python tools/build.py            rebuild docs/
    python tools/build.py --check    fail if docs/ is out of date

The old Windows app (server.py, the setup wizard) is in archive/ and no longer
built.
"""

import argparse
import hashlib
import os
import re
import shutil
import sys

DESIGNS = ["Minimal", "Classic", "Sharp", "Wide", "Slash", "Rainbow", "Modern", "Pulse", "Record"]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
WEB = os.path.join(SRC, "web")
DOCS = os.path.join(ROOT, "docs")

def read(path):
    with open(path, encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n")


# The size the setup page tells people to give each design's OBS Browser
# source: the card plus a little room, with the mode buttons kept just below
# it so viewers never see them. The overlay pages use the height too, to keep
# those buttons below it however tall the card is.
OBS_SIZES = {
    "Minimal": (680, 235),
    "Classic": (560, 245),
    "Sharp":   (600, 265),
    "Wide":    (640, 160),
    "Slash":   (600, 245),
    "Rainbow": (800, 220),
    "Modern":  (540, 194),
    "Pulse":   (660, 230),
    "Record":   (560, 210),
}

# The hooks a design's script is rewired through on the website. Each must be
# found exactly once in every design, or the build stops: a design that quietly
# kept polling a localhost server would just sit on "LOADING" in OBS.
WEB_SWAPS = [
    ("__POLL_MS__", "RankedOverlay.config.refreshMs"),
    ('"__INITIAL_CREATOR_CODE__"', "RankedOverlay.config.creatorCode"),
    ("fetch(url, { cache: 'no-store' })", "RankedOverlay.fetchData(url)"),
]
WEB_POLL = re.compile(r"setInterval\((?:tick|function\(\) \{ tick\(\); \})\s*,\s*POLL_MS\);")


# If engine.js didn't arrive (a network blip as OBS starts, say), the page
# would sit dead until someone refreshed the source by hand. Reload it instead,
# backing off from 5 seconds to a minute so a real outage isn't hammered.
ENGINE_GUARD = (
    "if (!window.RankedEngine) { var n = 0; "
    "try { n = +sessionStorage.getItem('ro-reloads') || 0; sessionStorage.setItem('ro-reloads', n + 1); } catch (e) {} "
    "setTimeout(function () { location.reload(); }, Math.min(60000, 5000 * Math.pow(2, n))); } "
    "else { try { sessionStorage.removeItem('ro-reloads'); } catch (e) {} }"
)


def asset_version(text):
    """Short content hash, so OBS never pairs a new page with an old engine."""
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:10]


def render_web_overlay(design, engine_version):
    """One design as a page of the hosted overlay."""
    html = read(os.path.join(SRC, "designs", design + ".html"))

    for old, new in WEB_SWAPS:
        if html.count(old) != 1:
            raise SystemExit(f"src/designs/{design}.html: expected one {old!r}, found {html.count(old)}")
        html = html.replace(old, new)

    if len(WEB_POLL.findall(html)) != 1:
        raise SystemExit(f"src/designs/{design}.html: expected one setInterval(tick, POLL_MS)")
    html = WEB_POLL.sub("RankedOverlay.onUpdate(tick);", html)

    if html.count("<script>") != 1:
        raise SystemExit(f"src/designs/{design}.html: expected exactly one <script> block")
    html = html.replace(
        "<script>",
        f'<script src="../engine.js?v={engine_version}"></script>\n'
        "    <script>" + ENGINE_GUARD + "</script>\n"
        "    <script>window.RankedOverlay = RankedEngine.startOverlay(location.search);</script>\n"
        "    <script>",
        1,
    )
    html = html.replace(
        "<head>",
        "<head>\n    <!-- Generated by tools/build.py from src/designs/"
        + design + ".html. Edit that file, not this one. -->\n"
        '    <meta name="robots" content="noindex">\n'
        # Keeps the Dark Reader extension from recolouring the overlay. (No
        # color-scheme "only light": Brave's night mode ignores it and then
        # paints the setup page's preview frame solid white.)
        '    <meta name="darkreader-lock">\n'
        f'    <meta name="obs-height" content="{OBS_SIZES[design][1]}">',
        1,
    )
    return html


def web_outputs():
    """The GitHub Pages site, as ({path: text}, {path: source file to copy})."""
    files, binaries = {}, {}
    engine = read(os.path.join(WEB, "engine.js"))
    version = asset_version(engine)

    files[os.path.join(DOCS, "engine.js")] = engine
    index = read(os.path.join(WEB, "index.html"))
    for hook in ("__ENGINE_GUARD__", "__OBS_SIZES__"):
        if index.count(hook) != 1:
            raise SystemExit(f"src/web/index.html: expected one {hook}")
    sizes = "{" + ", ".join(f"{d.lower()}: [{w}, {h}]" for d, (w, h) in OBS_SIZES.items()) + "}"
    files[os.path.join(DOCS, "index.html")] = (
        index.replace("__ENGINE_VERSION__", version)
             .replace("__ENGINE_GUARD__", ENGINE_GUARD)
             .replace("__OBS_SIZES__", sizes))
    files[os.path.join(DOCS, "logo.svg")] = read(os.path.join(WEB, "logo.svg"))
    # Serve the files as they are, without Jekyll looking at them first.
    files[os.path.join(DOCS, ".nojekyll")] = ""
    # The favicon and home-screen icon, rendered from logo.svg.
    for name in ("favicon-32.png", "apple-touch-icon.png", "og.png"):
        binaries[os.path.join(DOCS, name)] = os.path.join(WEB, name)

    for design in DESIGNS:
        slug = design.lower()
        files[os.path.join(DOCS, "overlay", slug + ".html")] = render_web_overlay(design, version)
        binaries[os.path.join(DOCS, "previews", slug + ".png")] = os.path.join(ROOT, "images", slug + ".png")
    return files, binaries


def write(path, text, newline="\n"):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline=newline) as f:
        f.write(text)


def same_bytes(a, b):
    try:
        with open(a, "rb") as fa, open(b, "rb") as fb:
            return fa.read() == fb.read()
    except OSError:
        return False


def current(path):
    try:
        with open(path, encoding="utf-8", newline="") as f:
            return f.read().replace("\r\n", "\n")
    except OSError:
        return None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report drift instead of rewriting anything")
    args = ap.parse_args()

    web_files, web_binaries = web_outputs()
    stale = [p for p, text in web_files.items() if current(p) != text]
    stale += [dst for dst, src in web_binaries.items() if not same_bytes(dst, src)]

    # Anything left in docs/ that the build no longer makes, e.g. a renamed design.
    owned = set(web_files) | set(web_binaries)
    orphans = []
    if os.path.isdir(DOCS):
        for folder, _dirs, names in os.walk(DOCS):
            for name in names:
                path = os.path.join(folder, name)
                if path not in owned:
                    orphans.append(path)

    total = len(web_files) + len(web_binaries)
    if args.check:
        if stale or orphans:
            print("These files in docs/ no longer match src/:\n")
            for p in sorted(stale + orphans):
                print("  " + os.path.relpath(p, ROOT))
            print("\nRun: python tools/build.py")
            return 1
        print(f"Up to date ({total} generated files).")
        return 0

    for p, text in web_files.items():
        write(p, text, newline="\n")
    for dst, src in web_binaries.items():
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)
    for p in orphans:
        os.remove(p)
    print(f"Wrote {total} files for {len(DESIGNS)} designs into docs/.")
    if stale:
        print(f"{len(stale)} of them changed.")
    if orphans:
        print(f"Removed {len(orphans)} stale file(s) from docs/.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
