#!/usr/bin/env python3
"""Generate the shipped overlay folders from src/.

Every design used to be a hand-maintained copy of the same 1800-line file, in
two places each: the folder people get from the repo zip, and the copy the
wizard builds from. Sixteen copies of one file meant sixteen edits per fix and
no way to notice when one of them drifted.

src/ is now the only place anything is written by hand:

    src/core_head.py     everything above the overlay markup
    src/designs/*.html   one file per design, just the markup
    src/core_tail.py       everything below it
    src/launcher/*.bat     the launcher, one copy
    src/config.default.json  the settings file a fresh install starts with

This script stitches those together into <Design>/ and wizard/templates/<Design>/.
Run it after touching anything in src/. CI runs it with --check to make sure the
generated folders in the repo actually match src/.

    python tools/build.py            rebuild everything
    python tools/build.py --check    fail if the repo is out of date
"""

import argparse
import os
import sys

DESIGNS = ["Minimal", "Classic", "Sharp", "Wide", "Slash", "Rainbow", "Modern", "Pulse"]
LAUNCHERS = ["overlay.bat"]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")

# Windows-only tool, and people open server.py in Notepad to check their
# settings, so everything ships with CRLF endings.
NEWLINE = "\r\n"

BANNER = (
    "# ---------------------------------------------------------------------------\n"
    "# Generated by tools/build.py from src/. Do not edit this file directly -- a\n"
    "# release would overwrite your changes. Edit src/core_head.py, src/core_tail.py\n"
    "# or src/designs/{design}.html instead, then run: python tools/build.py\n"
    "#\n"
    "# Your own settings do NOT live in this file. They live in config.json next to\n"
    "# it, which updates never touch.\n"
    "# ---------------------------------------------------------------------------\n"
)


def read(path):
    with open(path, encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n")


def render_server(design):
    """The full server.py for one design."""
    head = read(os.path.join(SRC, "core_head.py"))
    tail = read(os.path.join(SRC, "core_tail.py"))
    html = read(os.path.join(SRC, "designs", design + ".html"))

    if "__DESIGN__" not in head:
        raise SystemExit("src/core_head.py has lost its __DESIGN__ placeholder")
    head = head.replace("__DESIGN__", design)

    return (
        BANNER.replace("{design}", design)
        + head
        + "\n"
        + 'OVERLAY_HTML = r"""'
        + html
        + '"""\n'
        + tail
    )


def outputs():
    """Every file this script owns, as {path: text}."""
    files = {}
    launchers = {name: read(os.path.join(SRC, "launcher", name)) for name in LAUNCHERS}
    # Shipped filled in with placeholders so a fresh download has something to
    # edit straight away, rather than making people run the overlay once first.
    config = read(os.path.join(SRC, "config.default.json"))

    for design in DESIGNS:
        server = render_server(design)
        for parent in (ROOT, os.path.join(ROOT, "wizard", "templates")):
            folder = os.path.join(parent, design)
            files[os.path.join(folder, "server.py")] = server
            files[os.path.join(folder, "config.json")] = config
            for name, text in launchers.items():
                files[os.path.join(folder, name)] = text

    return files


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline=NEWLINE) as f:
        f.write(text)


def current(path):
    try:
        with open(path, encoding="utf-8", newline="") as f:
            return f.read().replace("\r\n", "\n")
    except OSError:
        return None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report drift instead of rewriting anything")
    args = ap.parse_args()

    files = outputs()
    stale = [p for p, text in files.items() if current(p) != text]

    if args.check:
        if stale:
            print("These generated files no longer match src/:\n")
            for p in sorted(stale):
                print("  " + os.path.relpath(p, ROOT))
            print("\nRun: python tools/build.py")
            return 1
        print(f"Up to date ({len(files)} generated files).")
        return 0

    for p, text in files.items():
        write(p, text)
    print(f"Wrote {len(files)} files for {len(DESIGNS)} designs.")
    if stale:
        print(f"{len(stale)} of them changed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
